services:
  app:
    build: .
    image: chat-app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
