ktor:
  application:
    modules:
      - learn.ktor.application.ApplicationKt.module
  deployment:
    port: 8080
  db:
    url: ${DB_URL}
    driver: org.postgresql.Driver
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    maxPoolSize: 10
  jwt:
    secret: ${JWT_SECRET}
    issuer: learn.ktor.chat
    audience: ktor-chat-api
    realm: Ktor Chat App
    expiration: 86400000
